[package]
name = "glass_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.12", features = [ "derive" ] }
log = "0.4.17"
simplelog = "0.12.0"
logos = "0.12.1"
snailquote = "0.3.1"
thiserror = "1.0.32"
git-version = "0.3.5"
line-span = "0.1.3"